"""
Diagram entity — represents a generated Mermaid.js diagram.
"""

from __future__ import annotations

import uuid
from enum import StrEnum

from pydantic import BaseModel, Field


class DiagramType(StrEnum):
    """Supported Mermaid diagram types."""

    CLASS = "class"
    SEQUENCE = "sequence"
    ER = "er"
    STATE = "state"
    ARCHITECTURE = "architecture"
    FLOWCHART = "flowchart"


class Diagram(BaseModel):
    """
    A single Mermaid.js diagram generated by the Diagrammer Agent.

    Attributes:
        id: Unique diagram identifier.
        document_id: The source SRS document this diagram belongs to.
        diagram_type: The type of Mermaid diagram.
        title: Human-readable title.
        mermaid_code: Raw Mermaid.js syntax string.
        is_valid: Whether the Mermaid syntax passed validation.
        validation_errors: Any syntax errors found during validation.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    document_id: str
    diagram_type: DiagramType
    title: str = ""
    mermaid_code: str = ""
    is_valid: bool = False
    validation_errors: list[str] = Field(default_factory=list)


class DiagramSet(BaseModel):
    """A collection of diagrams generated for a single SRS document."""

    document_id: str
    diagrams: list[Diagram] = Field(default_factory=list)

    @property
    def all_valid(self) -> bool:
        return all(d.is_valid for d in self.diagrams)
