"""
ZIP Builder — packages a ProjectScaffold into a downloadable ZIP archive.
"""

from __future__ import annotations

import zipfile
from pathlib import Path

from app.domain.entities.project_scaffold import ProjectScaffold


class ZipBuilder:
    """Builds a ZIP archive from a ProjectScaffold's generated files."""

    async def build(self, scaffold: ProjectScaffold, output_dir: Path) -> Path:
        """
        Create a ZIP file containing all generated scaffold files.

        Args:
            scaffold: The project scaffold with files to package.
            output_dir: Directory to write the ZIP into.

        Returns:
            Path to the created ZIP file.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        zip_filename = f"{scaffold.project_name}.zip"
        zip_path = output_dir / zip_filename

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            # Add a README at root
            readme_content = (
                f"# {scaffold.project_name}\n\n"
                f"Generated by Smart Documentation Architect.\n\n"
                f"## Directory Structure\n\n"
                f"```\n{scaffold.directory_tree}\n```\n"
            )
            zf.writestr(
                f"{scaffold.project_name}/README.md",
                readme_content,
            )

            # Add all generated files
            for gen_file in scaffold.files:
                arcname = f"{scaffold.project_name}/{gen_file.path}"
                zf.writestr(arcname, gen_file.content)

        return zip_path
